#!/bin/bash

if [[ "$(hyprctl getoption decoration:screen_shader | rg '\[\[EMPTY\]\]')" == '' ]]; then
	hyprctl keyword monitor ",preferred,auto,1"
	hyprctl keyword cursor:no_hardware_cursors false
	hyprctl keyword decoration:screen_shader '[[EMPTY]]'
else
	hyprctl keyword monitor ",preferred,auto,1.5"
	hyprctl keyword cursor:no_hardware_cursors true
	hyprctl keyword decoration:screen_shader '/home/flagrantior/.config/hypr/shaders/crt.frag'
fi
