[theme]
background = "black"
primary = "#ff00ff"
secondary = "#ff00ff"
title = "#00ffff"
playing = "#00ffff"
playing_selected = "#00ffff"
playing_bg = "black"
highlight = "#ffffff"
highlight_bg = "black"
error = "light white"
error_bg = "red"
statusbar = "#00ffff"
statusbar_bg = "#000000"
statusbar_progress = "#00ffff"
statusbar_progress_bg = "#000000"
cmdline = "#00ffff"
cmdline_bg = "black"

[keybindings]
"Shift+Right" = "seek +10000"
"Shift+Left" = "seek -10000"
"Tab" = "move right 1"
"Shift+Tab" = "move left 1"
" " = "playpause"
"," = "previous"
"." = "next"
