swipe:
  3:
    left:
      command: "swaymsg -r workspace prev"
    right:
      command: "swaymsg -r workspace next"
    up:
      update:
        command: "pactl set-sink-volume 0 +5%"
    down:
      update:
        command: "pactl set-sink-volume 0 -5%"
  4:
    up:
      update:
        command: "light -A 1"
    down:
      update:
        command: "light -U 1"

interval:
  swipe: 0.5
