gui:
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  skipUnstageLineWarning: false
  skipStashWarning: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: true
  mainPanelSplitMode: flexible
  theme:
    lightTheme: false
    activeBorderColor:
    - cyan
    - bold
    inactiveBorderColor:
    - magenta
    optionsTextColor:
    - blue
    selectedLineBgColor:
    - default
    selectedRangeBgColor:
    - blue
  commitLength:
    show: true
  skipNoStagedFilesWarning: false
